api_platform:
    formats:
        json:
            mime_types: [ 'application/json' ]
        html:
            mime_types: [ 'text/html' ]
    resource_class_directories:
        - '%kernel.project_dir%/src/'
    patch_formats:
        json: ['application/merge-patch+json']
        jsonapi:  ['application/vnd.api+json']

    enable_entrypoint: false
    enable_re_doc: false
    enable_swagger_ui: false